In [1]:
import numpy as np

In [33]:
list1=np.random.rand(2,3)
list2=np.random.rand(2,3)
list1

array([[0.55642947, 0.39355085, 0.74267559],
       [0.58128839, 0.15979421, 0.18664909]])

#### Transposing Array

In [7]:

i = np.transpose(list1) #Permute array dimensions
#i.T #Permute array dimensions
i

array([[0.88956199, 0.08609392],
       [0.48049996, 0.38562421],
       [0.44909577, 0.39783423]])

#### Changing Array Shape

In [8]:

list1.ravel() #Flatten the array

 

array([0.88956199, 0.48049996, 0.44909577, 0.08609392, 0.38562421,
       0.39783423])

In [11]:
list1.reshape(3,-2) #Reshape, but don’t change data

array([[0.64900033, 0.84868346],
       [0.0902446 , 0.07950715],
       [0.40306402, 0.59343437]])

#### Adding/Removing Elements


In [13]:
#list1.resize((2,6)) #Return a new array with shape (2,6)



In [ ]:
np.append(h,g) #Append items to an array
np.insert(a, 1, 5) #Insert items in an array
np.delete(a,[1]) #Delete items from an array

#### Combining Arrays

In [15]:

np.concatenate((list1,list2),axis=0) #Concatenate arrays


 

array([[0.28141132, 0.64152365, 0.29551715],
       [0.82895819, 0.90921931, 0.35079881],
       [0.62992166, 0.22751954, 0.67398675],
       [0.16041267, 0.54387965, 0.78355382]])

In [16]:
np.vstack((list1,list2)) #Stack arrays vertically (row-wise)



array([[0.28141132, 0.64152365, 0.29551715],
       [0.82895819, 0.90921931, 0.35079881],
       [0.62992166, 0.22751954, 0.67398675],
       [0.16041267, 0.54387965, 0.78355382]])

In [17]:
np.r_[list1,list2] #Stack arrays vertically (row-wise)


array([[0.28141132, 0.64152365, 0.29551715],
       [0.82895819, 0.90921931, 0.35079881],
       [0.62992166, 0.22751954, 0.67398675],
       [0.16041267, 0.54387965, 0.78355382]])

In [18]:
np.hstack((list1,list2)) #Stack arrays horizontally (column-wise)



array([[0.28141132, 0.64152365, 0.29551715, 0.62992166, 0.22751954,
        0.67398675],
       [0.82895819, 0.90921931, 0.35079881, 0.16041267, 0.54387965,
        0.78355382]])

In [19]:
np.column_stack((list1,list2)) #Create stacked column-wise arrays



array([[0.28141132, 0.64152365, 0.29551715, 0.62992166, 0.22751954,
        0.67398675],
       [0.82895819, 0.90921931, 0.35079881, 0.16041267, 0.54387965,
        0.78355382]])

In [20]:
np.c_[list1,list2] #Create stacked column-wise arrays

array([[0.28141132, 0.64152365, 0.29551715, 0.62992166, 0.22751954,
        0.67398675],
       [0.82895819, 0.90921931, 0.35079881, 0.16041267, 0.54387965,
        0.78355382]])

#### Splitting Arrays

In [28]:
list3=np.array([1,2,3,4,5,6,7,7,8,9,10,11,12,13,14,15])
np.hsplit(list3,2) #Split the array horizontally at the 3rd



[array([1, 2, 3, 4, 5, 6, 7, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15])]

In [36]:
np.vsplit(list1,2) #Split the array vertically at the 2nd index


[array([[0.55642947, 0.39355085, 0.74267559]]),
 array([[0.58128839, 0.15979421, 0.18664909]])]

In [35]:
list1

array([[0.55642947, 0.39355085, 0.74267559],
       [0.58128839, 0.15979421, 0.18664909]])

In [37]:
list3=np.array([1,2,3,4,5,6,7,7,8,9,10,11,12,13,14,15])