In [4]:
import numpy as np
import pandas as pd


### random.rand
GENERATES RANDOM NUMBERS

(2,3,4)
2= number of rows
3= number of column
4= no of values

In [5]:
data = np.random.rand(2,3,4)
data

array([[[0.27258924, 0.95946823, 0.82898651, 0.56154772],
        [0.28499987, 0.07965192, 0.42898475, 0.96848054],
        [0.62579326, 0.10936053, 0.55074546, 0.95331429]],

       [[0.14895497, 0.56996796, 0.87928551, 0.91293159],
        [0.41200947, 0.01535148, 0.91025961, 0.50560608],
        [0.07580464, 0.81138967, 0.18673174, 0.96817326]]])

### zeros
generates row of zeros

In [8]:
zeroes = np.zeros((2,2,2))
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

### full
generates rows of given number

In [9]:
full = np.full((2,2,2), 7)
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

### one
generates rows of ones

In [10]:
ones = np.ones((2,2,2))
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

### 2-D random.rand

In [28]:
data = np.random.rand(2,2)
data

array([[0.93419063, 0.31088582],
       [0.95768967, 0.44314336]])

In [29]:
pd.DataFrame(data)

0         1
0  0.934191  0.310886
1  0.957690  0.443143

In [43]:
np.zeros((3,4)) #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones((2,3,4),dtype=np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

### arange
problem with arange is to do casting or due to using floating points when start is much larger than step. This can lead to unexpected behaviour.
andthe other prblem is memory result in incorrect results for large integer values.



In [34]:
np.arange(10,25,5) #Create an array of evenly spaced values (step value)

array([10, 15, 20])

In [37]:
np.arange(0, 5, 0.5, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### linspace
use linspace for that purpose instead 

In [44]:
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Create an array of evenly spaced values (number of samples)

### eye
2X2 identity matrix

In [38]:
np.eye(2) #Create a 2X2 identity matrix

array([[1., 0.],
       [0., 1.]])

In [39]:
np.random.random((2,2)) #Create an array with random values

array([[0.42147974, 0.68358475],
       [0.54951042, 0.11321444]])

In [41]:
np.empty((3,2)) 

array([[0.50004397, 0.86914736],
       [0.94859486, 0.77574946],
       [0.89751328, 0.85404409]])