In [1]:
import numpy as np

In [2]:
data = np.random.rand(2,3,4)

In [11]:
data2 = np.random.rand(2,3,4)

In [3]:
np.delete(data, 0, axis=1)


array([[[0.54400999, 0.67231374, 0.9668899 , 0.50433331],
        [0.98555563, 0.56712504, 0.04186846, 0.4014088 ]],

       [[0.88121346, 0.65347748, 0.8520115 , 0.51105343],
        [0.08650482, 0.64212354, 0.85045038, 0.00793927]]])

In [4]:
np.save("new array", data)

In [5]:

test = np.load("new array.npy")

In [6]:
test

array([[[0.11472922, 0.45480401, 0.83716575, 0.59848879],
        [0.54400999, 0.67231374, 0.9668899 , 0.50433331],
        [0.98555563, 0.56712504, 0.04186846, 0.4014088 ]],

       [[0.45340582, 0.79958454, 0.28386611, 0.55697363],
        [0.88121346, 0.65347748, 0.8520115 , 0.51105343],
        [0.08650482, 0.64212354, 0.85045038, 0.00793927]]])

In [8]:
h=data.view() #Create a view of the array with the same data
h

array([[[0.11472922, 0.45480401, 0.83716575, 0.59848879],
        [0.54400999, 0.67231374, 0.9668899 , 0.50433331],
        [0.98555563, 0.56712504, 0.04186846, 0.4014088 ]],

       [[0.45340582, 0.79958454, 0.28386611, 0.55697363],
        [0.88121346, 0.65347748, 0.8520115 , 0.51105343],
        [0.08650482, 0.64212354, 0.85045038, 0.00793927]]])

In [9]:
np.copy(data) #Create a copy of the array
#or
h = data.copy() 


### Saving & Loading On Disk


In [10]:
np.save('my_array', data)


In [12]:
np.savez('array.npz', data, data2)


In [16]:
np.load('array.npz')

### text files

In [18]:
data2d=np.random.rand(2,3)
data2d

array([[0.53669547, 0.92382354, 0.99891023],
       [0.9724958 , 0.71379441, 0.66343798]])

In [20]:
np.savetxt("myarray.txt", data2d, delimiter=" ")

In [21]:
np.loadtxt("myarray.txt")

array([[0.53669547, 0.92382354, 0.99891023],
       [0.9724958 , 0.71379441, 0.66343798]])

In [ ]:
#csv
np.genfromtxt("my_file.csv", delimiter=',')