In [1]:
import numpy as np

### Two lists

In [2]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [6]:
add = np.add(list1, list2)
list1+list2

array([0.40842421, 1.01307021, 0.61296562, 0.83478795, 1.5389524 ,
       0.93327592, 1.14571935, 1.10218029, 0.95988908, 0.95193151])

In [4]:
sub = np.subtract(list1, list2)
list1-list2

array([ 0.25163285, -0.09439006,  0.21666691,  0.27432357,  0.21796472,
        0.56632489,  0.57269428, -0.81409085,  0.37648661,  0.57240682])

In [5]:
div = np.divide(list1, list2)
list1/list2

array([4.20977944, 0.82953779, 2.09345249, 1.97891529, 1.33000266,
       4.08665109, 2.99884551, 0.15033856, 2.29065827, 4.0164405 ])

In [7]:
mult = np.multiply(list1, list2)
list1*list2

array([0.02587281, 0.25435044, 0.08219558, 0.15540437, 0.58021647,
       0.13757001, 0.24617352, 0.13801437, 0.19491122, 0.14463101])

In [8]:
dot = np.dot(list1, list2)
dot

1.9593398020370925

### Arithmetic Operations

In [9]:
np.exp(list1)

array([1.39100781, 1.58302896, 1.51409253, 1.74116731, 2.40718632,
       2.11657751, 2.36128701, 1.15493575, 1.95069915, 2.14291953])

In [10]:
 np.sqrt(list1)

array([0.57448109, 0.67774632, 0.64406232, 0.74468501, 0.9372612 ,
       0.86591016, 0.92693409, 0.37953224, 0.81742758, 0.87302301])

In [11]:
np.sin(list1)

array([0.32407002, 0.44335668, 0.40302179, 0.52656569, 0.76975584,
       0.6814927 , 0.75732482, 0.14354711, 0.61956456, 0.69049211])

In [12]:
np.cos(list1)

array([0.9460331 , 0.89634528, 0.91519038, 0.85013445, 0.63833843,
       0.73182491, 0.65303837, 0.98964349, 0.7849457 , 0.72333992])

In [13]:
np.log(list1)

array([-1.10857618, -0.77796444, -0.87991959, -0.58958792, -0.12958654,
       -0.28794824, -0.15174562, -1.93763149, -0.40318594, -0.27158674])

In [14]:
mins = np.min(list1)
maxs = np.max(list1)
mins,maxs

(0.14404471776398398, 0.8784585639178178)

In [15]:
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)


sqrt,ab,power

(5.0, 2, 128)

In [16]:
list1.sort()

In [17]:
list1

array([0.14404472, 0.33002853, 0.41481627, 0.45934007, 0.55455576,
       0.66818785, 0.7498004 , 0.76216917, 0.85920682, 0.87845856])

In [19]:
list1[0]=12

In [26]:
list1.sort(axis=0)

In [27]:
list1

array([ 0.33002853,  0.41481627,  0.45934007,  0.55455576,  0.66818785,
        0.7498004 ,  0.76216917,  0.85920682,  0.87845856, 12.        ])

### AGGREGATE

In [28]:
list1.sum() #Array-wise sum


17.6765634254513

In [29]:
list1.min() #Array-wise minimum value


0.33002852769502633

In [30]:
list1.max(axis=0) #Maximum value of an array row


12.0

In [32]:
#list1.cumsum(axis=1) #Cumulative sum of the elements


In [33]:
list1.mean() #Mean


1.76765634254513

In [40]:
#list1.median() #Median



In [39]:
#list1.corrcoef() #Correlation coefficient


In [36]:
list1

array([ 0.33002853,  0.41481627,  0.45934007,  0.55455576,  0.66818785,
        0.7498004 ,  0.76216917,  0.85920682,  0.87845856, 12.        ])

In [37]:
np.std(list1) 

3.415449173817817